# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 383f9deab6f1fe9c95602552e73c8cfa1776988d20cb176f8e4c242d6ee1422c02888ab9f7f244262e57ea5e87ffb1e5ff7517ab8e4a837b5da15c09e510e101

test:
  secret_key_base: fb0f2b159bce1291f66baedaea02aada2f185cbbd65b0624f2d4c04ddec9c3b7c6116caa92877f597bb92af8b8101a72b37bd56e1d9639b3980bdec673c0e72c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
